const Colors = {
  light: {
    tabColor:"#a0e7ff",
    PrimaryColor: "#34ccff",
    text: "#000000D9",
    link: "#33CCFF",
    blue: "#115ABB",
    Hiddengray: "#828282",
    background: "#fff",
    backgroundGray: "#f6f6f6",
    backgroundActive: "#f0feff",
    onlineGreen: "#18BD5A",
    AddMemberGreen: "#18BD5A",
    backgroundMessage: "#32A4EE",
    backgroundMessageQuestion: "#f0f0f0",
    tintText: "#00000073",
    grayText: "#717171",
    black: "black",
    gray: "#e5e5e5",
    lightText: "#fff",
    formItemBorder: "#d9d9d9",
    formItemBorderFocused: "#5cdcff",
    tableHeadBg: "#fafafa",
    error: "#ff4d4f",
    warn: "#ec942c",
    HighLighter: "#F3F9FC",
    LightBlue: "#F3F9FC",
    White: "#FFFF",
    normalGray: "gray",
    PhoneNoColor: "#828282",
    red: "#FF7D7D",
    alertSuccess: "#3c8c58",
    alertFailure: "#a8312f",
  },
  dark: {
    text: "#fff",
    background: "#000000D9",
    overlay: "rgba(0,0,0,.7)",
  },
  transparent: "transparent",
};

export default Colors;
