export let realmErrors = {
  200: "Session closed (no error)",
  201: "Other session level error",
  202: "Access token expired",
  203: "Bad user authentication (BIND)",
  204: "Illegal Realm path (BIND)",
  205: "No such Realm (BIND)",
  206: "Permission denied (BIND)",
  207: "Bad server file identifier (IDENT) (obsolete)",
  208: "Bad client file identifier (IDENT)",
  209: "Bad server version (IDENT, UPLOAD)",
  210: "Bad client version (IDENT, UPLOAD)",
  211: "Diverging histories (IDENT)",
  212: "Bad changeset (UPLOAD)",
  213: "Disabled session (BIND, IDENT, UPLOAD, MARK)",
  214: "Partial sync disabled (BIND)",
  215: "Unsupported session-level feature",
  216: "Bad origin file identifier (UPLOAD)",
  217: "Synchronization no longer possible for client-side file",
  218: "Server file was deleted while session was bound to it",
  219: "Client file has been blacklisted (IDENT)",
  220: "User has been blacklisted (BIND)",
  221: "Serialized transaction before upload completion",
  222: "Client file has expired",
  223: "User mismatch for client file identifier (IDENT)",
  224: "Too many sessions in connection (BIND)",
  225: "Invalid schema change (UPLOAD)",
  226: "Client query is invalid/malformed (IDENT, QUERY)",
  227: "Client tried to create an object that already exists outside their view (UPLOAD)",
  228: "Server permissions for this file ident have changed since the last time it was used (IDENT)",
  229: "Client tried to open a session before initial sync is complete (BIND)",
  230: "Client attempted a write that is disallowed by permissions, or modifies an \
object outside the current query - requires client reset (UPLOAD)	",
  231: "Client attempted a write that is disallowed by permissions, or modifies an \
object outside the current query, and the server undid the modification (UPLOAD)	",
  232: "Server migrated from PBS to FLX - migrate client to FLX (BIND)",
  233: "Bad progress information (ERROR)",
  234: "Server rolled back to PBS after FLX migration - revert FLX client migration (BIND)",
};
