export enum DocsTypes {
  pptx = "pptx",
  ppt = "ppt",
  pdf = "pdf",
  docx = "docx",
  csv = "csv",
  xls = "xls",
  doc = "doc",
  pages = "pages",
  numbers = "numbers",
  key = "key",
  txt = "txt",
}

export const DocIcons = {
  zip: require("../../assets/images/MessageIcons/zip.png"),
  txt: require("../../assets/images/MessageIcons/txt.png"),
  xls: require("../../assets/images/MessageIcons/sheets.png"),
  xlsx: require("../../assets/images/MessageIcons/sheets.png"),
  ppt: require("../../assets/images/MessageIcons/ppt.png"),
  pptx: require("../../assets/images/MessageIcons/ppt.png"),
  png: require("../../assets/images/MessageIcons/image.png"),
  pdf: require("../../assets/images/MessageIcons/pdf.png"),
  jpeg: require("../../assets/images/MessageIcons/image.png"),
  jpg: require("../../assets/images/MessageIcons/image.png"),
  doc: require("../../assets/images/MessageIcons/docs.png"),
  docx: require("../../assets/images/MessageIcons/docs.png"),
  csv: require("../../assets/images/MessageIcons/csv.png"),
  mp3: require("../../assets/images/MessageIcons/audio.png"),
  other: require("../../assets/images/MessageIcons/allfile.png"),
  mp4: require("../../assets/images/MessageIcons/video.png"),
  mpeg: require("../../assets/images/MessageIcons/video.png"),
  avi: require("../../assets/images/MessageIcons/video.png"),
  "3gp": require("../../assets/images/MessageIcons/video.png"),
  mov: require("../../assets/images/MessageIcons/video.png"),
};
